# Generated by Django 3.2.23 on 2024-01-25 03:44

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tours',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
