# Generated by Django 3.2.23 on 2024-01-25 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_tag_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tours',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='tours',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
