# Generated by Django 3.2.23 on 2024-01-25 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20240125_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tours',
            name='discount_price',
        ),
        migrations.RemoveField(
            model_name='tours',
            name='price',
        ),
        migrations.CreateModel(
            name='PricingOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_name', models.CharField(max_length=255)),
                ('option_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('special_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('includes', models.JSONField(blank=True, null=True)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_options', to='core.tours')),
            ],
        ),
    ]
